export const BASE_URL = "https://horse.mvp-apps.ae/";

export const NEWS_LIST = "NEWS_LIST";
export const NEWS_LIST_SUCCESS = "NEWS_LIST_SUCCESS";
export const NEWS_LIST_FAILURE = "NEWS_LIST_FAILURE";

export const FAQ_LIST = "FAQ_LIST";
export const FAQ_SUCCESS = "FAQ_SUCCESS";
export const FAQ_FAILURE = "FAQ_FAILURE";

export const UPCOMING_EVENT = "UPCOMING_EVENT";
export const UPCOMING_EVENT_SUCCESS = "UPCOMING_EVENT_SUCCESS";
export const UPCOMING_EVENT_FAILURE = "UPCOMING_EVENT_FAILURE";

export const PAST_EVENTS = "PAST_EVENTS";
export const PAST_EVENTS_SUCCESS = "PAST_EVENTS_SUCCESS";
export const PAST_EVENTS_FAILURE = "PAST_EVENTS_FAILURE";

export const EVENT_CALENDAR = "EVENT_CALENDAR";
export const EVENT_CALENDAR_SUCCESS = "EVENT_CALENDAR_SUCCESS";
export const EVENT_CALENDAR_FAILURE = "EVENT_CALENDAR_FAILURE";